title = "Willem Vooijs"
baseURL = 'https://willem.vooijs.eu/'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = 'G-FFEE1FZEXZ' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Willem Vooijs"
  defaultColor = "dark" # set default color mode: dark or light
  description = "Willem Vooijs's personal blog"
  mainSections = ['posts']

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Hi, I'm Willem Vooijs."
  name = "Willem Vooijs"
  description = "Product Manager by profession. I love tinkering with electronics, home automation, open source software and sustainable energy."

[[params.socialIcons]]
name = "github"
url = "https://github.com/wildekek"

[[params.socialIcons]]
name = "x"
url = "https://twitter.com/wildekek"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/willemvooijs/"